steps: 900
initial_population:
  r_a: 10
transitions: vignettes/infect_example_confit/tick_transitions.csv
parameters: vignettes/infect_example_confit/tick_parameters.csv
host_comm: vignettes/infect_example_confit/host_den.csv
