steps: 1200
initial_population:
  r_a: 10
transitions: inputs/2021-03-19_Dave_test/tick_transitions.csv
parameters: inputs/2021-03-19_Dave_test/tick_parameters.csv
weather: inputs/2021-03-19_Dave_test/weather.csv
host_comm: inputs/2021-03-19_Dave_test/host_comm.csv
