steps: 500
initial_population:
  r_a: 10
transitions: host_example_config/tick_transitions.csv
parameters: host_example_config/tick_parameters.csv
weather: host_example_config/weather.csv
host_comm: host_example_config/host_comm.csv
