steps: 500
initial_population:
  r_a: 10
transitions: data-raw/host_example_config/tick_transitions.csv
parameters: data-raw/host_example_config/tick_parameters.csv
predictors: data-raw/host_example_config/predictors.csv
