steps: 500
initial_population:
  r_a: 10
transitions: data-raw/infect_example_config/tick_transitions.csv
parameters: data-raw/infect_example_config/tick_parameters.csv
predictors: data-raw/infect_example_config/predictors.csv
